config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :posts, only: [:index, :show] do
    resources :comments, only: :create
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :content, :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :nickname, presence: true
  validates :nickname, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: "Commentaire créé avec succès !"
    else
      redirect_to @post, alert: "Merci de rentrer un commentaire"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_post, only: %i[show]
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSharePosts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="banner">
    <div class="container">
      <h1>Explorez, Découvrez, Partagez: Votre Source Infinie d'Inspiration !</h1>
      <p>Découvrez un monde d'articles captivants et informatifs sur une variété de sujets passionnants.</p>
      <%= link_to "Voir tous les articles", posts_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <p class="mt-4"><%= link_to "<< Retour à la page d'accueil", root_path, class: "retour" %></p>
  <h1 style="font-size: 40px" id="titre">Liste des publications</h1>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= link_to post_path(post) do %>
        <div class="card-posts">
          <div class="card-title mt-2">
            <h4><%= post.title %></h1>
            <p><%= truncate(post.content, length: 250) %>(...)</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
 <div class="container mb-5">
  <p><%= link_to "<< Retour aux articles", posts_path, class:"retour mb-2 mt-4" %></p>
  <div id="show">
    <h1><%= @post.title %></h1>
    <h5><em>Auteur :</em> <strong><%= @post.user.nickname.capitalize %></strong></h3>
    <p id="lien">Source: <a href="<%= @post.url %>" target="_blank" id="source" ><%= @post.url %></a></p>
    <p style="font-size: 20px"><%= @post.content %></p>

    <h3 class="mt-5">Commentaires</h5>
    <div class="comments mb-4">
      <% if @post.comments.any? %>
        <% @post.comments.each do |comment| %>
          <em>Écrit par: </em><strong><%= comment.user.nickname %></strong><br>
          <p style="white-space: pre-line; word-wrap: break-word;"><%= comment.content %></p>
        <% end %>
      <% else %>
        <p style="font-size: 16px"><em>Aucun commentaire</em></p>
      <% end %>
    </div>

    <div id="contact">
      <%= simple_form_for [@post, @comment] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= f.input :content, as: :text, label: "Ajouter un commentaire" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Publier", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <h1>InfoLink</h1>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link me-4" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-regular fa-user avatar fa-2x" style="color: #000000;"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Tableau de bord de #{current_user.nickname}", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <button class="btn btn-primary">Login</button>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>